name: pet_lover
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  device_preview:
  font_awesome_flutter:
  image_picker:
  path_provider:
  image_cropper:
  cloud_firestore:
  intl:
  firebase_core:
  shared_preferences: ^2.0.6
  firebase_storage:
    # For Video Added
  video_player: ^2.1.15
  file_picker:
  uuid:
  provider:
  firebase_auth:
  pull_to_refresh:
  firebase_messaging:
  image_downloader: ^0.30.0
  flutter_downloader: ^1.6.1
  permission_handler: ^8.1.4+2
  dio:
  image_gallery_saver:
  chewie: ^1.2.2
  visibility_detector:
  video_compress:
  change_app_package_name: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  fonts:
    - family: MateSC
      fonts:
        - asset: fonts/MateSC-Regular.ttf
    - family: DancingScript
      fonts:
        - asset: fonts/DancingScript-VariableFont.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
